---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana
  namespace: monitoring
  labels:
    team: frontend
spec:
  endpoints:
  - honorLabels: true
    port: http-grafana
  selector:
    matchLabels:
      app: grafana
