ingress-nginx:
  controller:
    replicaCount: 2
    service:
      type: LoadBalancer
    admissionWebhooks:
      enabled: true
    extraArgs:
      enable-ssl-passthrough: ""

cert-manager:
  installCRDs: true
  webhook:
    enabled: true
  cainjector:
    enabled: true
  startupapicheck:
    enabled: true
