---
- name: Install Monitoring Tools on AWS EKS Nodes
  hosts: eks_nodes
  become: yes
  tasks:
    - name: Ensure Helm is installed
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        executable: /bin/bash
      register: helm_install_result
      ignore_errors: true
      changed_when: "'Helm v3' in helm_install_result.stdout"

    - name: Add Helm repositories
      shell: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo update
      register: helm_repo_update_result
      changed_when: "'Update Complete' in helm_repo_update_result.stdout"

    - name: Install Prometheus
      shell: |
        helm install prometheus prometheus-community/prometheus \
          --namespace monitoring \
          --create-namespace
      args:
        chdir: /tmp
      register: prometheus_install_result
      changed_when: "'STATUS: deployed' in prometheus_install_result.stdout"

    - name: Install Grafana
      shell: |
        helm install grafana grafana/grafana \
          --namespace monitoring \
          --create-namespace
      args:
        chdir: /tmp
      register: grafana_install_result
      changed_when: "'STATUS: deployed' in grafana_install_result.stdout"

    - name: Install Alertmanager
      shell: |
        helm install alertmanager prometheus-community/alertmanager \
          --namespace monitoring \
          --create-namespace
      args:
        chdir: /tmp
      register: alertmanager_install_result
      changed_when: "'STATUS: deployed' in alertmanager_install_result.stdout"
