apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-rules
  namespace: monitoring
  labels:
    role: alert-rules
spec:
  groups:
  - name: prometheus.rules
    rules:
    - alert: PrometheusHighCPUUsage
      annotations:
        description: "Prometheus instance {{ $labels.instance }} is using more than 80% of CPU."
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheushighcpuusage
        summary: "High CPU usage detected in Prometheus instance."
      expr: |
        (rate(container_cpu_usage_seconds_total{job="prometheus", instance=~".*"}[5m]) * 100)
        > 80
      for: 5m
      labels:
        severity: critical

    - alert: PrometheusHighMemoryUsage
      annotations:
        description: "Prometheus instance {{ $labels.instance }} is using more than 80% of memory."
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheushighmemoryusage
        summary: "High memory usage detected in Prometheus instance."
      expr: |
        (container_memory_usage_bytes{job="prometheus", instance=~".*"} / container_spec_memory_limit_bytes{job="prometheus", instance=~".*"})
        * 100
        > 80
      for: 5m
      labels:
        severity: critical

    - alert: PrometheusHighQueryDuration
      annotations:
        description: "Prometheus query duration is above 2 seconds on instance {{ $labels.instance }}."
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheushighqueryduration
        summary: "High query duration detected in Prometheus instance."
      expr: |
        histogram_quantile(0.95, rate(prometheus_http_query_duration_seconds_bucket{job="prometheus"}[5m]))
        > 2
      for: 5m
      labels:
        severity: warning

    - alert: PrometheusScrapeErrors
      annotations:
        description: "Prometheus instance {{ $labels.instance }} has high scrape errors."
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheusscrapeerrors
        summary: "High number of scrape errors detected in Prometheus instance."
      expr: |
        rate(prometheus_scrape_errors_total{job="prometheus"}[5m])
        > 0.05
      for: 5m
      labels:
        severity: warning

    - alert: PrometheusDiskSpaceLow
      annotations:
        description: "Prometheus instance {{ $labels.instance }} has low disk space."
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/prometheus/prometheusdiskspacelow
        summary: "Low disk space detected in Prometheus instance."
      expr: |
        (node_filesystem_free{job="node", mountpoint="/prometheus"} / node_filesystem_size{job="node", mountpoint="/prometheus"})
        * 100
        < 10
      for: 5m
      labels:
        severity: critical
