apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
    route:
      group_by: 
       - cluster
      - alertname
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: 'slack-notifications'
      routes:
      - matchers:
        - severity = warning
        receiver: 'slack-notifications'
      - matchers:
        - severity = critical
        receiver: 'slack-notifications'
    receivers:
    - name: 'slack-notifications'
      slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#alerts'
        send_resolved: true
        title: "[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}"
        text: "{{ range .Alerts }}\n*Alert:* {{ .Annotations.summary }}\n*Description:* {{ .Annotations.description }}\n*Severity:* {{ .Labels.severity }}\n*Timestamp:* {{ .StartsAt }}\n{{ end }}"
type: Opaque
